# general settings
name: 052_ESRGAN_x4_f64b23_DIV2K_400k_B16G1_Weighted_UnetDisc
model_type: ESRGANTrainModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: WaveletPairedImageDataset
    dataroot_gt: train/DIV2K/DIV2K_train_HR
    dataroot_lq: train/DIV2K/DIV2K_train_LR_bicubic/X4
    dataroot_weight: train/DIV2K/DIV2K_train_std
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}x4'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: train/benchmark/Set14/HR
    dataroot_lq: train/benchmark/Set14/LR_bicubic/X4
    filename_tmpl: '{}x4'
    dataroot_weight: 
    io_backend:
      type: disk

# network structures
network_g:
  type: MyRRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

network_w:
  type: WeightMapNonNorm3FT
  ndim_norm: 1

# path
path:
  pretrain_network_g: train/pretrained_models/RRDB_PSNR_x4.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 150000]
    gamma: 0.5

  total_iter: 160000
  warmup_iter: -1  # no warm up

  weightgan:
    quantile: 0
    gamma: 1
    apply_vgg: 0
    apply_d: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3
    var_weight: true

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
    niqe:
      type: calculate_niqe
      crop_border: 4
      better: lower

# logging settings
logger:
  print_freq: 2500
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
